#! /bin/bash
#Script pour initialier les liens et les submodules

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
ln -siv "${DIR}""/.vimrc"  "$HOME"/.vimrc
ln -siv "${DIR}""/vim"  "$HOME"/.vim
ln -siv "${DIR}""/sublime-text-3/Packages"  "$HOME"/.config/sublime-text-3/Packages

git submodule init
git submodule update

for D in "${DIR}""/vim/bundle/"* ; do
    if [ -d "${D}" ]; then
      echo  "${D}"

    fi
done
